CONTRIB_POST_TYPES = [
    'tumblelog.contrib.audio.Rdio',
    'tumblelog.contrib.audio.SoundCloud',
    'tumblelog.contrib.code.Gist',
    'tumblelog.contrib.file.File',
    'tumblelog.contrib.link.Link',
    'tumblelog.contrib.photo.Image',
    'tumblelog.contrib.photo.Flickr',
    'tumblelog.contrib.photo.Instagram',
    'tumblelog.contrib.text.Text',
    'tumblelog.contrib.text.Article',
    'tumblelog.contrib.twitter.Tweet',
    'tumblelog.contrib.video.YouTube',
    'tumblelog.contrib.video.Vimeo',
]
